#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SERVICE_DIFY_PORT text "Port" 8080

  service::config_set SERVICE_DIFY_SECRET_KEY text "Secret Key" $(os::uuid)
}

check $@
